DROP DATABASE contactbook;
CREATE SCHEMA contactbook;
SET NAMES utf8;

USE contactbook;

CREATE TABLE User (
  ID   BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  LOGIN   VARCHAR(64)      NOT NULL,
  PASSWORD    VARCHAR(60),
  FIO       VARCHAR(10),
  ENABLE   BOOLEAN DEFAULT true NOT NULL,
  CREDENTIALSEXPIRED   BOOLEAN DEFAULT true NOT NULL,
  LOCKED   BOOLEAN DEFAULT false NOT NULL,
  PRIMARY KEY (ID),
  CONSTRAINT uq_user_login UNIQUE (LOGIN)
);

CREATE TABLE Contact (
  ID    BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
  NAME   VARCHAR(20)      NOT NULL,
  SECONDNAME    VARCHAR(20) NOT NULL,
  THIRDNAME    VARCHAR(20),
  MOBILEPHONE       VARCHAR(15),
  HOMEPHONE       VARCHAR(15),
  ADDRESS    VARCHAR(50),
  EMAIL       VARCHAR(100),
  PRIMARY KEY (ID)
);

CREATE TABLE Role (
  ID   BIGINT UNSIGNED NOT NULL,
  ROLE   VARCHAR(64)      NOT NULL,
  PRIMARY KEY (ID)
);

CREATE TABLE UserRole (
user_id BIGINT UNSIGNED NOT NULL,
role_id BIGINT UNSIGNED NOT NULL,
PRIMARY KEY (user_id, role_id),
CONSTRAINT FK_USER FOREIGN KEY (user_id) REFERENCES User (ID),
CONSTRAINT FK_ROLE FOREIGN KEY (role_id) REFERENCES Role (ID)
);

INSERT INTO role (ROLE) VALUES ('AMDIN');
INSERT INTO role (ROLE) VALUES ('USER');