CREATE SCHEMA contactbook;
SET NAMES utf8;

USE contactbook;

CREATE TABLE `user` (
  `ID`   INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `LOGIN`   VARCHAR(64)      NOT NULL,
  `PASSWORD`    VARCHAR(512),
  `FIO`       VARCHAR(10)
);

CREATE TABLE `contact` (
  `ID`    INT(10) UNSIGNED NOT NULL AUTO_INCREMENT PRIMARY KEY,
  `NAME`   VARCHAR(20)      NOT NULL,
  `SECONDNAME`    VARCHAR(20) NOT NULL,
  `THIRDNAME`    VARCHAR(20),
  `MOBILEPHONE`       VARCHAR(15),
  `HOMEPHONE`       VARCHAR(15),
  `ADDRESS`    VARCHAR(50),
  `EMAIL`       VARCHAR(100)
  );
